apiVersion: v1
kind: Secret
metadata:
  name: gitea-token
  namespace: argo
type: Opaque
stringData:
  token: ""

apiVersion: v1
kind: Secret
metadata:
  name: gitea-creds
  namespace: argo
type: Opaque
stringData:
  username: ""
  password: ""

